### ISSUE TITLE
Rapspeed and Rapboard Javascript engines UCI

### ISSUE THREAD

**Issue by yellow-panther** [Thibor/Chess-Engine-Rapchess#2]
Hello Thibor,

are Rapspeed and Rapboard engines no longer available on your website or did their names changed into Rapchess - Rapshort - Rapsimple etc.?

**Comment by Thibor** [comment]
Hi. I found error in engin Rapspeed and this engin was not strong so I delete it, now best engin is Rapchess,, Rapboard changed name on Rapsimple. In demo I used engin Rapsimple to control board, and Rapchess as opponent.
