### ISSUE TITLE
How to check if the user won?

### ISSUE THREAD

**Issue by satya4satyanm** [Thibor/Chess-Engine-Rapchess#5]
Hi Thibor,

I love this game engine. I love the way its coded.

Getting some difficulty in placing a condition to check if any user won.

If any opponent wins there are no message displayed. Can you please help.

Thank you
Satya

**Comment by Thibor** [comment]
Message who won should be at the very bottom. I think about it maybe I add something else.

**Comment by Thibor** [comment]
Now I added extra info who win in centre of window, should be better. Thank you for your comments.

**Comment by satya4satyanm** [comment]
Excellent. Thank you.

**Comment by satya4satyanm** [comment]
Can u please check in the code. I was eager to see how its implemented.
