### ISSUE TITLE
Rapchess.js does not work with Arena GUI via JSUCI

### ISSUE THREAD

**Issue by ShubusCorporation** [Thibor/Chess-Engine-Rapchess#6]
Rapchess.js does not work with Arena GUI via Jsuci.  Jsuci versions are checked: 1.2 (last) and 1. At the same time, p4wn engine shipped with Jsuci works.

**Comment by Thibor** [comment]
i check it and it work. you can check type of error in engines/log - window, or you can just type in command line "jsuci rapchess.js", after in console you can write "uci" for test. if is any error program jsuci usually show type of error and number of wrong line in code.

**Comment by ShubusCorporation** [comment]
Oh, it seems, my version of Rapchess was outdated. I've updated it and it works. Thank you!
